#!/usr/bin/env bash 
#Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend milanenterprise.tech_frontend
        bind *:80
        mode http
        default_backend milanenterprise.tech_backend
backend milanenterprise.tech_backend
        balance roundrobin
        server 451827-web-01 54.237.16.172:80 check
        server 451827-web-02 54.237.100.72:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the HAProxy service
sudo service haproxy restart
