#!/usr/bin/env bash
# This script lists the content of the current directory.
#   Only displays the part of the name after the first dash. 

lst=$(ls)
for i in $lst; do
  echo "$i" | cut -d '-' -f2
done
